
export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Jammu & Kashmir",
  "Ladakh",
];

export const VENDOR_CATEGORIES = [
  "CATERING",
  "DECOR",
  "PHOTOGRAPHY",
  "VIDEOGRAPHY",
  "VENUE",
  "ENTERTAINMENT",
  "DJ_MUSIC",
  "TRANSPORTATION",
  "FLORALS",
  "MAKEUP_ARTIST",
  "MEHENDI",
  "SOUND_LIGHTING",
  "INVITATION_DESIGN",
  "CAKE_BAKERY",
  "SECURITY",
  "ANCHOR_HOST",
  "OTHER",
];

export const CATEGORY_LABELS: Record<string, string> = {
  CATERING:"Catering", 
  DECOR:"Decor", 
  PHOTOGRAPHY:"Photography",
  VIDEOGRAPHY:"Videography", 
  VENUE:"Venue", 
  ENTERTAINMENT:"Entertainment",
  DJ_MUSIC:"DJ & Music", 
  TRANSPORTATION:"Transportation", 
  FLORALS:"Florals",
  MAKEUP_ARTIST:"Makeup Artist", 
  MEHENDI:"Mehendi", 
  SOUND_LIGHTING:"Sound & Lighting",
  INVITATION_DESIGN:"Invitation Design", 
  CAKE_BAKERY:"Cake & Bakery",
  SECURITY:"Security", 
  ANCHOR_HOST:"Anchor & Host", 
  OTHER:"Other",
};

// shared select className — used in multiple form cards
export const SELECT_CLS = "flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring";

export const TEXTAREA_CLS = "w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring resize-none placeholder:text-muted-foreground";